//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RentACarProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rezervasyonlar
    {
        public int rezID { get; set; }
        public Nullable<System.DateTime> rezTarih { get; set; }
        public Nullable<System.TimeSpan> rezSaat { get; set; }
        public Nullable<int> uyeID { get; set; }
        public Nullable<int> aracID { get; set; }
    
        public virtual Araclar Araclar { get; set; }
        public virtual Uyeler Uyeler { get; set; }
    }
}
