//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RentACarProject.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;//validation iþlemleri için eklendi.

    public partial class Rezervasyonlar
    {
        public int rezID { get; set; }

        [Required(ErrorMessage = "Lütfen rezervasyon tarihini giriniz.")] //gerekli kýsým
        [Display(Name = "Alýþ Tarihi")]//Bu ekranda görünen isim
        public Nullable<System.DateTime> rezTarih { get; set; }

        [Required(ErrorMessage = "Lütfen rezervasyon saatini giriniz.")] //gerekli kýsým
        [Display(Name = "Alýþ Saati")]//Bu ekranda görünen isim
        public Nullable<System.TimeSpan> rezSaat { get; set; }

        [Required(ErrorMessage = "Lütfen teslim tarihini giriniz.")] //gerekli kýsým
        [Display(Name = "Teslim Tarihi")]//Bu ekranda görünen isim
        public Nullable<System.DateTime> rezTeslimTarih { get; set; }

        [Required(ErrorMessage = "Lütfen teslim saatini giriniz.")] //gerekli kýsým
        [Display(Name = "Teslim Saati")]//Bu ekranda görünen isim
        public Nullable<System.TimeSpan> rezTeslimSaat { get; set; }

        public Nullable<int> uyeID { get; set; }
        public Nullable<int> aracID { get; set; }
    
        public virtual Araclar Araclar { get; set; }
        public virtual Uyeler Uyeler { get; set; }
    }
}
