//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RentACarProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Subeler
    {
        public int subeID { get; set; }
        public string subeAdi { get; set; }
        public string subeAdres { get; set; }
        public Nullable<int> subeTelefon { get; set; }
    }
}
