//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RentACarProject.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;//validation iþlemleri için eklendi.

    public partial class Uyeler
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Uyeler()
        {
            this.Rezervasyonlar = new HashSet<Rezervasyonlar>();
        }
    
        public int uyeID { get; set; }

        [Required(ErrorMessage = "Lütfen üye adýný giriniz.")] //gerekli kýsým
        [Display(Name = "Adý")]//Bu ekranda görünen isim
        public string uyeAd { get; set; }

        [Required(ErrorMessage = "Lütfen üye sayadýný giriniz.")] //gerekli kýsým
        [Display(Name = "Sayadý")]//Bu ekranda görünen isim
        public string uyeSoyad { get; set; }

        [Required(ErrorMessage = "Lütfen üye mail adresini giriniz.")] //gerekli kýsým
        [Display(Name = "Email")]//Bu ekranda görünen isim
        public string uyeEmail { get; set; }

        [Required(ErrorMessage = "Lütfen üye þifresini giriniz.")] //gerekli kýsým
        [Display(Name = "Þifre")]//Bu ekranda görünen isim
        public string uyeSifre { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Rezervasyonlar> Rezervasyonlar { get; set; }
    }
}
